name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: bitacoramtto
  REGION: us-central1
  REPOSITORY: bitacoramtto-repo
  SERVICE: bitacora-app

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Auth to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker
        run: gcloud auth configure-docker $REGION-docker.pkg.dev

      - name: Build and Push
        run: |
          docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$SERVICE .
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$SERVICE

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE \
            --image $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$SERVICE \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated